from datetime import datetime
from enum import Enum
from pydantic import BaseModel


class AIItemType(str, Enum):
    """Type of AI-generated item."""

    EVENT = "event"
    TASK = "task"
    IDEA = "idea"


class AIPriority(str, Enum):
    """Priority level for AI items."""

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class ModificationType(str, Enum):
    """Type of plan modification."""

    ADJUSTMENT = "adjustment"
    RESTRUCTURE = "restructure"


# --- Request Models ---


class AIGenerateRequest(BaseModel):
    """Request body for AI plan generation."""

    goal_text: str


# --- Gemini Response Models (parsed from JSON) ---


class AIGeneratedItem(BaseModel):
    """Individual item generated by Gemini."""

    id: str
    type: AIItemType
    title: str
    scheduled_date: str | None = None  # ISO date string
    scheduled_time: str | None = None  # ISO datetime string
    end_time: str | None = None  # ISO datetime string
    estimated_minutes: int | None = None
    is_flexible: bool
    purpose: str
    explanation: str
    category: str | None = None
    priority: AIPriority | None = None


class GeminiPlanResponse(BaseModel):
    """Structured response from Gemini API."""

    plan_id: str
    generated_at: str  # ISO datetime string
    summary: str
    modification_type: ModificationType
    reasoning: str | None = None
    items: list[AIGeneratedItem]


# --- Firestore Document Models ---


class UserGoalInput(BaseModel):
    """User's goal input stored with the plan."""

    raw_text: str
    goal: str | None = None
    background: str | None = None
    strengths: str | None = None
    weaknesses: str | None = None
    timeline: str | None = None

    def to_firestore_dict(self) -> dict:
        return {
            "raw_text": self.raw_text,
            "goal": self.goal,
            "background": self.background,
            "strengths": self.strengths,
            "weaknesses": self.weaknesses,
            "timeline": self.timeline,
        }


class PlanStatus(str, Enum):
    """Status of a plan."""

    ACTIVE = "active"
    MODIFIED = "modified"
    ARCHIVED = "archived"


class PlanDocument(BaseModel):
    """Plan document stored in Firestore."""

    id: str
    user_id: str
    user_input: UserGoalInput
    summary: str
    status: PlanStatus = PlanStatus.ACTIVE
    generated_at: datetime
    created_at: datetime
    updated_at: datetime

    def to_firestore_dict(self) -> dict:
        return {
            "id": self.id,
            "user_id": self.user_id,
            "user_input": self.user_input.to_firestore_dict(),
            "summary": self.summary,
            "status": self.status.value,
            "generated_at": self.generated_at,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


class EventSource(str, Enum):
    """Source of an event."""

    MANUAL = "manual"
    AI_GENERATED = "aiGenerated"


class EventDocument(BaseModel):
    """Event document stored in Firestore."""

    id: str
    user_id: str
    plan_id: str | None
    title: str
    description: str | None = None
    scheduled_date: datetime
    start_time: datetime
    end_time: datetime
    location: str | None = None
    source: EventSource
    purpose: str | None = None
    explanation: str | None = None
    is_completed: bool = False
    created_at: datetime
    updated_at: datetime

    def to_firestore_dict(self) -> dict:
        return {
            "id": self.id,
            "user_id": self.user_id,
            "plan_id": self.plan_id,
            "title": self.title,
            "description": self.description,
            "scheduled_date": self.scheduled_date,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "location": self.location,
            "source": self.source.value,
            "purpose": self.purpose,
            "explanation": self.explanation,
            "is_completed": self.is_completed,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


class TaskSource(str, Enum):
    """Source of a task."""

    MANUAL = "manual"
    AI_GENERATED = "aiGenerated"


class TaskDocument(BaseModel):
    """Task document stored in Firestore."""

    id: str
    user_id: str
    plan_id: str | None
    title: str
    description: str | None = None
    scheduled_date: datetime | None = None
    scheduled_time: datetime | None = None
    estimated_minutes: int | None = None
    source: TaskSource
    purpose: str | None = None
    explanation: str | None = None
    is_completed: bool = False
    completed_at: datetime | None = None
    created_at: datetime
    updated_at: datetime

    def to_firestore_dict(self) -> dict:
        return {
            "id": self.id,
            "user_id": self.user_id,
            "plan_id": self.plan_id,
            "title": self.title,
            "description": self.description,
            "scheduled_date": self.scheduled_date,
            "scheduled_time": self.scheduled_time,
            "estimated_minutes": self.estimated_minutes,
            "source": self.source.value,
            "purpose": self.purpose,
            "explanation": self.explanation,
            "is_completed": self.is_completed,
            "completed_at": self.completed_at,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


# --- API Response Models ---


class GeneratedItemResponse(BaseModel):
    """Single generated item in API response."""

    id: str
    type: AIItemType
    title: str
    scheduled_date: str | None
    scheduled_time: str | None
    end_time: str | None
    estimated_minutes: int | None
    is_flexible: bool
    purpose: str
    explanation: str
    category: str | None
    priority: AIPriority | None


class AIGenerateResponse(BaseModel):
    """Response from AI generation endpoint."""

    plan_id: str
    summary: str
    items: list[GeneratedItemResponse]
    events_created: int
    tasks_created: int
    tokens_remaining: int
