import Foundation

// MARK: - AI Response

/// The structured JSON response from the Gemini AI planning engine.
/// All AI responses must conform to this schema.
struct AIResponse: Codable {
    let planId: String
    let generatedAt: Date
    let summary: String
    let items: [AIGeneratedItem]

    // Metadata about the generation
    let modificationType: ModificationType
    let reasoning: String?       // AI's reasoning for this plan structure
}

// MARK: - AI Generated Item

/// Individual item generated by the AI (can be event, task, or idea)
struct AIGeneratedItem: Codable, Identifiable {
    let id: String
    let type: AIItemType
    let title: String

    // Scheduling
    let scheduledDate: Date?     // Specific date (required for events)
    let scheduledTime: Date?     // Specific time (required for events)
    let endTime: Date?           // End time (required for events)
    let estimatedMinutes: Int?   // Duration estimate (for tasks)
    let isFlexible: Bool         // If true, user decides when

    // Context
    let purpose: String          // Why this advances the user's goal
    let explanation: String      // Detailed paragraph

    // Optional
    let category: String?        // Category for organization
    let priority: AIPriority?    // Suggested priority level
}

// MARK: - AI Item Type

enum AIItemType: String, Codable {
    case event   // Time-bound, day-locked
    case task    // Flexible, user-scheduled
    case idea    // Suggestion for consideration
}

// MARK: - AI Priority

enum AIPriority: String, Codable {
    case high
    case medium
    case low
}

// MARK: - Conversion to Domain Models

extension AIGeneratedItem {
    /// Convert AI-generated item to an Event
    func toEvent(userId: String, planId: String) -> Event? {
        guard type == .event,
              let date = scheduledDate,
              let start = scheduledTime,
              let end = endTime else {
            return nil
        }

        return Event(
            id: id,
            userId: userId,
            planId: planId,
            title: title,
            description: nil,
            scheduledDate: date,
            startTime: start,
            endTime: end,
            location: nil,
            source: .aiGenerated,
            purpose: purpose,
            explanation: explanation,
            isCompleted: false
        )
    }

    /// Convert AI-generated item to a Task
    func toTask(userId: String, planId: String) -> Task? {
        guard type == .task || type == .idea else {
            return nil
        }

        return Task(
            id: id,
            userId: userId,
            planId: planId,
            title: title,
            description: nil,
            scheduledDate: isFlexible ? nil : scheduledDate,
            scheduledTime: isFlexible ? nil : scheduledTime,
            estimatedMinutes: estimatedMinutes,
            source: .aiGenerated,
            purpose: purpose,
            explanation: explanation,
            isCompleted: false
        )
    }
}

extension AIResponse {
    /// Convert all items to domain models
    func toDomainModels(userId: String) -> (events: [Event], tasks: [Task]) {
        var events: [Event] = []
        var tasks: [Task] = []

        for item in items {
            if let event = item.toEvent(userId: userId, planId: planId) {
                events.append(event)
            } else if let task = item.toTask(userId: userId, planId: planId) {
                tasks.append(task)
            }
        }

        return (events, tasks)
    }
}

// MARK: - JSON Coding Keys

extension AIResponse {
    enum CodingKeys: String, CodingKey {
        case planId = "plan_id"
        case generatedAt = "generated_at"
        case summary
        case items
        case modificationType = "modification_type"
        case reasoning
    }
}

extension AIGeneratedItem {
    enum CodingKeys: String, CodingKey {
        case id
        case type
        case title
        case scheduledDate = "scheduled_date"
        case scheduledTime = "scheduled_time"
        case endTime = "end_time"
        case estimatedMinutes = "estimated_minutes"
        case isFlexible = "is_flexible"
        case purpose
        case explanation
        case category
        case priority
    }
}
